### ISSUE TITLE
Using the Grappling Hook on a dedicated server creates a ticking entity

### ISSUE THREAD

**Issue by WordStormRose** [squeeglii/grapplemod-restitched#18] opened 2024-03-20 23:26 UTC
## Versions:

 - The Grapple Hook Mod:  1.20(.1)-v1.7
 - Minecraft:  1.20.1
 - Mod Loader:  Forge (47.2.19) with Sinytra Connector (1.0.0-beta.39+1.20.1) and Forgified Fabric API (0.92.0+1.11.3+1.20.1)

## Description:

So I switched to using this version of Grappling Hook today because I found out the Forge version doesn't work in the forge version I need to use for one of my other mods, and while it works fine in singleplayer, I run an smp and in the process of testing this on that server, when I tried to use the hook Neruina reported it as a ticking entity. Thinking it was maybe a mistake despite how many times it happened, I disabled Neruina's feature of killing ticking entities and then when I tried again the server crashed.
I tested it afterward with just what was required for Grapple Hook to work, and I _would_ have tested it in just fabric, but my modpack needs forge for the overwhelming majority of other mods.

https://pastebin.com/ruaTKFCt <- the crashlog from when the server had my whole modpack
https://pastebin.com/DPYk6jbt <- crashlog from when both the server and my instance had only the required mods

**Comment by squeeglii** [comment] 2024-03-21 02:03
Typically I avoid fixing issues when this port of the mod is used with forge as it can be unpredictable, but the cause seems pretty straightforward here and it may cause issues with Fabric in the future. I'm fairly certain this isn't a bug in a pure fabric environment but comments are welcome.

Fixing this won't happen on v1.x as it'll require a large refactor, which v2.0 is already doing. I'll see how much work it needs. 

It'll be a while before a fix is even shipped so I recommend trying to make the forge mod work 🙏 - it just requires an older version of the mod loader if I remember correctly but that can be a pain.

**Comment by WordStormRose** [comment] 2024-03-21 02:58
Unfortunately the older forge version will cause issues other mods I have so I'll just need to remove it and re-add when v2.0 of this version comes out, but thank you!

**Comment by squeeglii** [comment] 2024-04-11 18:46
Should be fixed! Turns out fabric was bumping into the same issue. :)

I've brought a lot of the 2.0 changes forward so if you want something working sooner, there's 1.99.0 for 1.20.1:
https://modrinth.com/mod/grappling-hook-mod-fabric/version/1.99.0+1.20.1.beta.fabric

**Closed as completed by squeeglii** 2024-04-11 18:46 UTC
Labels: bug, incompatibility

**Comment by Leclowndu93150** [comment] 2024-04-13 09:45
Can't update until this gets on github

**Comment by squeeglii** [comment] 2024-04-13 10:14
> Can't update until this gets on github

if you're looking for the source, see pre/v2-cdr-preview-1.20.1

If you're looking for a release, I'm only chucking it on modrinth for now (see the link to the exact release above). I don't do GitHub releases for my main set of mods & curseforge can wait until I know v2 is fully stable. 

It's only available for 1.20.1 at the moment but I'll be working on porting it to other versions soon. I don't believe this bug is present in all versions so you could try downgrading grapplemod in the meantime? v1.6 seemed pretty stable at the time.

Hope that clears things up.

**Comment by Leclowndu93150** [comment] 2024-04-13 12:22
i meant curseforge sorry, im so tired
