### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by defautluser0** [squeeglii/grapplemod-restitched#3] opened 2023-03-04 19:41 UTC
**Describe the bug**
When i load quilt it crashes

**Version**
Include the versions for:
- The Grapple Hook Mod - 1.5
- The Mod Loader - Quilt 0.18.4 beta, qfapi 4.0.0
- Minecraft 1.19.2

**Output Log And Crash Report**
[crash-2023-03-04_20.39.31.4808-quilt_loader.txt](https://github.com/CloudG360/grapplemod-restitched/files/10889501/crash-2023-03-04_20.39.31.4808-quilt_loader.txt)
[latest.log](https://github.com/CloudG360/grapplemod-restitched/files/10889500/latest.log)

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. Load Minecraft
2. Crash

**Comment by squeeglii** [comment] 2023-03-04 22:48
Hiya! I did a little review of the log and found:

- This mod doesn't mess with the area affected
- The issue is with Valkyrien Skies
  - I think you're using a version of the mod for 1.18 
  - The code in that area has changed between 1.18 and 1.19.2
  
I can't seem to find a version of Valkyrien Skies for 1.19.2 so you might be out of luck till they update! Seems like work is still underway there though so hopefully the wait isn't too long. There's a version of this mod and Valkyrien Skies for 1.18.2 so, with a downgrade of all the other mods, you could try that. :)

Closing the issue there.

**Closed as completed by squeeglii** 2023-03-04 22:48 UTC
Labels: invalid
